Coinbase prime orders and wallets APIs
forus-coop/coinbase-prime-node pull request #2
Opened 2022-07-07 10:44 UTC by synerzipprasann

@forus-coop/developers

## Asana or Jira Ticket

## What's the Problem You're Solving?
Implement coinbase-prime node package to fetch coinbase prime APIs

## Fix
- Added all endpoints of Orders API
- Added all endpoints of Wallets API

## Testing

## Checklist
- [x] 1 PR, 1 purpose: my Pull Request applies to a single purpose
  - [ ] This PR only contains configuration changes
  - [ ] This PR only contains code changes (if configuration changes are required, do a separate PR first, then rebase)
- [ ] My code follows the style guidelines, including naming conventions
- [ ] I have commented my code with YARD docs
- [ ] I have added explanatory comments, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have performed a self-review of my own code

2022-07-07 18:21 UTC, scottmuhs requested changes
looking good, can we add some tests?

2022-07-11 10:43 UTC, synerzipprasann commented
Hi @scottmuhs, I have added specs as you suggest, Could you please review it, when you get chance.

2022-07-12 21:54 UTC, scottmuhs approved these changes
Few Comments...can we name test failes as `fileName.test.ts` instead of spec.
Also all types/interfaces should be Capitalized

2022-07-12 21:54 UTC, scottmuhs commented on src/lib/activities.ts
> +type listParams = {
Capitalized

2022-07-12 21:54 UTC, scottmuhs commented on src/lib/orders.ts
> +type openOrdersParams = {
Caps

2022-07-12 21:54 UTC, scottmuhs commented on src/lib/orders.ts
> +type createParams = {
Caps

2022-07-13 08:44 UTC, merged