Coinbase prime Assets and Transactions APIs
forus-coop/coinbase-prime-node pull request #3
Opened 2022-07-07 11:21 UTC by ManojParmarForusall

@forus-coop/developers

## Asana or Jira Ticket

## What's the Problem You're Solving?
Implement coinbase-prime node package to fetch coinbase prime APIs

## Fix
- Added Assets endpoints
- Added Transactions endpoints

## Testing

## Checklist
- [ ] 1 PR, 1 purpose: my Pull Request applies to a single purpose
  - [ ] This PR only contains configuration changes
  - [ ] This PR only contains code changes (if configuration changes are required, do a separate PR first, then rebase)
- [ ] My code follows the style guidelines, including naming conventions
- [ ] I have commented my code with YARD docs
- [ ] I have added explanatory comments, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have performed a self-review of my own code

2022-07-07 18:33 UTC, scottmuhs requested changes
Can we add some tests?

2022-07-07 18:33 UTC, scottmuhs commented on src/lib/transactions.ts
> +    const res = await this.get(operationalUrl, params);
do wanna wrap this in try/catch?

2022-07-07 18:33 UTC, scottmuhs commented on src/lib/util.ts
> +import * as _ from 'lodash';
if you are using webpack to roll this up, we can utilize tree shaking, instead of import lodash file...i would maybe suggest doing something more like `import {isUndefined} from 'lodash'` or `import isUndefined from 'lodash/isUndefined'`

2022-07-07 18:33 UTC, scottmuhs commented on src/lib/util.ts
> +import * as _ from 'lodash';
the latter results in a smaller bundle size

2022-07-12 21:56 UTC, scottmuhs approved these changes
All types/interfaces should be capitalized. looking good

2022-07-13 07:37 UTC, triveni21 commented
Capitalized types.

2022-07-13 07:38 UTC, merged